<section class="forminfo1 clearfix full mb40">
	<div class="l_sec pull-left">
		<div class="row clearfix">
			<div class="lsec">COMPANY NAME:</div> <div class="rsec">Accessories by Stephanie</div>
		</div>

		<div class="row clearfix"><div class="lsec">SHIP TO ADDRESS:</div> <div class="rsec"><p>142 W.36th Street<br>
		New York, NY 10018</p></div></div>

		<div class="row clearfix"><div class="lsec">BILL TO ADDRESS:</div> <div class="rsec"><p>142 W.36th Street<br>
		New York, NY 10018</p></div></div>

		<div class="row clearfix"><div class="lsec">BUYER’S NOTES:</div> <div class="rsec"><p>I have a fashion event, please let me know if all items are ready to ship.  Please use my
		credit card ending 1234.8</p></div></div>

		<div class="half pull-left">
			<div class="row clearfix">
				<div class="lsec wid_auto">START DATE:</div> <div class="rsec wid_auto"><p>ASAP</p>
			</div></div>
		</div>
		<div class="half pull-right">
			<div class="row clearfix pull-right"><div class="lsec wid_auto nowrap">COMPLETION DATE:</div> <div class="rsec wid_auto">4/1/15
		</div></div>
	</div>

</div>

<div class="r_sec pull-right">
	<div class="row clearfix"><div class="lsec">PO#:</div> <div class="rsec">A1234</div></div>

	<div class="row clearfix"><div class="lsec">TERMS:</div> <div class="rsec">CREDIT CARD ending 5122</div></div>

	<div class="row clearfix"><div class="lsec">BUYERS EMAIL:</div> <div class="rsec">buyer@stephaniebyacc.com</div></div>

	<div class="row clearfix"><div class="lsec">ACCOUNT EXECUTIVE:</div> <div class="rsec">Ashley Rock</div></div>

	<div class="row clearfix">
		<div class="lsec wid_auto"><small>TOTAL  (without shipping):</small>
			<span class="total text-center wid_auto">$2340.00</span>
		</div> 

	</div>

	<!--<button class="btn btn-primary btn-large pull-right">CREATE<br/>LINK</button>-->
	
</div>

</section>

<section class="cartview clearfix">
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<th align="left">Style</th>
			<th align="center">Description</th>
			<th align="left" class="color">Color</th>
			<th align="left">Size Scale</th>
			<th align="center">Unit<br>
				Cost</th>
				<th align="center">Total<br>
					QTY</th>
					<th align="center">Total<br>
						Cost</th>
					</tr>
					<tr>
						<td align="left" class="style">DR12</td>
						<td align="center" class="desc">geo floral print cowl drape soft knit dress with hem sleeves</td>
						<td colspan="2" align="right" class="color productlist">
							
							<div class="sizes">
								<ul class="mb0">
									<li></li>
									<li><small>XS</small></li>
									<li><small>S</small></li>
									<li><small>M</small></li>
									<li><small>L</small></li>
									<li><small>XL</small></li>
									<li><small>1X</small></li>
								</ul>

								<div class="clearfix"></div>

								<ul>
									<li class="text-right">Black</li>
									<li><input type="text" name=""></li>
									<li><input type="text" value="2"></li>
									<li><input type="text" value="2"></li>
									<li><input type="text" value="2"></li>
									<li><input type="text" name=""></li>
									<li><input type="submit" value="SOLD
										OUT" name="" disabled="" class="soldout"></li>
									</ul>
									<div class="clearfix"></div>

								</div>

							</td>
							<td colspan="3" align="center" class="unitcost productlist"><div class="sizes"><ul class="subtot">
								<li>$39.00 x</li><li><input type="text" value="10"></li><li>= $234</li>
							</ul></div></td>
						</tr>
						
						<tr>
							<td align="left" class="style">DR12</td>
							<td align="center" class="desc">geo floral print cowl drape soft knit dress with hem sleeves</td>
							<td colspan="2" align="right" class="color productlist">
								
								<div class="sizes">
									<ul class="mb0">
										<li></li>
										<li><small>XS</small></li>
										<li><small>S</small></li>
										<li><small>M</small></li>
										<li><small>L</small></li>
										<li><small>XL</small></li>
										<li><small>1X</small></li>
									</ul>

									<div class="clearfix"></div>

									<ul>
										<li class="text-right">Black</li>
										<li><input type="text" name=""></li>
										<li><input type="text" value="2"></li>
										<li><input type="text" value="2"></li>
										<li><input type="text" value="2"></li>
										<li><input type="text" name=""></li>
										<li><input type="submit" value="SOLD
											OUT" name="" disabled="" class="soldout"></li>
										</ul>
										<div class="clearfix"></div>

										<ul>
											<li class="text-right brown_txt">BROWN</li>
											<li><input type="text" name=""></li>
											<li><input type="text" value="1"></li>
											<li><input type="text" value="1"></li>
											<li><input type="text" value="2"></li>
											<li><input type="text" name=""></li>
											<li><input type="text" name=""></li>
										</ul>
										<div class="clearfix"></div>
									</div>

								</td>
								<td colspan="3" align="center" class="unitcost productlist"><div class="sizes"><ul class="subtot">
									<li>$39.00 x</li><li><input type="text" value="10"></li><li>= $234</li>
								</ul></div></td>
							</tr>
							
							<tr>
								<td align="left" class="style">DR12</td>
								<td align="center" class="desc">geo floral print cowl drape soft knit dress with hem sleeves</td>
								<td colspan="2" align="right" class="color productlist">
									
									<div class="sizes">
										<ul class="mb0">
											<li></li>
											<li><small>XS</small></li>
											<li><small>S</small></li>
											<li><small>M</small></li>
											<li><small>L</small></li>
											<li><small>XL</small></li>
											<li><small>1X</small></li>
										</ul>

										<div class="clearfix"></div>

										<ul>
											<li class="text-right">Black</li>
											<li><input type="text" name=""></li>
											<li><input type="text" value="2"></li>
											<li><input type="text" value="2"></li>
											<li><input type="text" value="2"></li>
											<li><input type="text" name=""></li>
											<li><input type="submit" value="SOLD
												OUT" name="" disabled="" class="soldout"></li>
											</ul>
											<div class="clearfix"></div>

											<ul>
												<li class="text-right">Black</li>
												<li><input type="text" name=""></li>
												<li><input type="text" value="2"></li>
												<li><input type="text" value="2"></li>
												<li><input type="text" value="2"></li>
												<li><input type="text" name=""></li>
												<li><input type="submit" value="SOLD
													OUT" name="" disabled="" class="soldout"></li>
												</ul>
												<div class="clearfix"></div>

												<ul>
													<li class="text-right brown_txt">BROWN</li>
													<li><input type="text" name=""></li>
													<li><input type="text" value="1"></li>
													<li><input type="text" value="1"></li>
													<li><input type="text" value="2"></li>
													<li><input type="text" name=""></li>
													<li><input type="text" name=""></li>
												</ul>
												<div class="clearfix"></div>
											</div>

										</td>
										<td colspan="3" align="center" class="unitcost productlist"><div class="sizes"><ul class="subtot">
											<li>$39.00 x</li><li><input type="text" value="10"></li><li>= $234</li>
										</ul></div></td>
									</tr>
									
									<tr>
										<td align="left" class="style">DR12</td>
										<td align="center" class="desc">geo floral print cowl drape soft knit dress with hem sleeves</td>
										<td colspan="2" align="right" class="color productlist">
											
											<div class="sizes">
												<ul class="mb0">
													<li></li>
													<li><small>XS</small></li>
													<li><small>S</small></li>
													<li><small>M</small></li>
													<li><small>L</small></li>
													<li><small>XL</small></li>
													<li><small>1X</small></li>
												</ul>

												<div class="clearfix"></div>

												<ul>
													<li class="text-right">Black</li>
													<li><input type="text" name=""></li>
													<li><input type="text" value="2"></li>
													<li><input type="text" value="2"></li>
													<li><input type="text" value="2"></li>
													<li><input type="text" name=""></li>
													<li><input type="submit" value="SOLD
														OUT" name="" disabled="" class="soldout"></li>
													</ul>
													<div class="clearfix"></div>

													<ul>
														<li class="text-right brown_txt">BROWN</li>
														<li><input type="text" name=""></li>
														<li><input type="text" value="1"></li>
														<li><input type="text" value="1"></li>
														<li><input type="text" value="2"></li>
														<li><input type="text" name=""></li>
														<li><input type="text" name=""></li>
													</ul>
													<div class="clearfix"></div>
												</div>

											</td>
											<td colspan="3" align="center" class="unitcost productlist"><div class="sizes"><ul class="subtot">
												<li>$39.00 x</li><li><input type="text" value="10"></li><li>= $234</li>
											</ul></div></td>
										</tr>
									</table>

								</section>