


<?php	if( $this->order_links_id ):
	$url = $this->url('order', array('id' => $order_links_id), array('force_canonical' => false)); 
	$message = 'Your Order linki is http://bsp.local'.$url;

?>
	<section class="forminfo1 full clearfix success text-center">
  		<h2>Your order link is : <a href="<?php echo $this->server_url.$url;?>"><?php echo $this->server_url.$url;?></a></h2>
	</section>
<?php endif; ?>	
	
<form  method="post"  >

<section class="forminfo1 full clearfix">

<?php //echo $url = $this->url('order', array('id' => 999), array('force_canonical' => false)); ?>


	<?php

	/*$form = $this->form;
	$name = $form->get('name');
	 echo $this->formInput($name);
	 echo $this->formElementErrors($name);*/
?>

		<div class="l_sec pull-left">

			<label for="textfield"></label>
			<?php echo $this->formInput( $this->form->get('name') ); ?>
			<?php echo $this->formElementErrors()
						->setMessageOpenFormat('<span class="error">')
						->setMessageCloseString('</span>')
						->render($form->get('name')); 
			?>

			<label for="textfield"></label>
			<?php echo $this->formTextArea( $this->form->get('ship_to') ); ?>
			<?php echo $this->formElementErrors($form->get('ship_to')); ?>

			<label for="textfield"></label>
			<?php echo $this->formTextArea( $this->form->get('bill_to') ); ?>
			<?php echo $this->formElementErrors($form->get('bill_to')); ?>

			<?php echo $this->formTextArea( $this->form->get('notes') ); ?>	
			<?php echo $this->formElementErrors($form->get('notes')); ?>

			<span><label for="textfield"></label>
			<?php echo $this->formInput( $this->form->get('start_date') ); ?>
			<?php echo $this->formElementErrors($form->get('start_date')); ?></span>

			<span class="pull-right"><label for="textfield"></label>
			<?php echo $this->formInput( $this->form->get('end_date') ); ?>
			<?php echo $this->formElementErrors($form->get('end_date')); ?></span>

		</div>
		
		<div class="r_sec pull-right">
			<label for="textfield"></label>
			<?php echo $this->formInput( $this->form->get('po') ); ?>
			<?php echo $this->formElementErrors($form->get('po')); ?>

			<label for="textfield"></label>
			<?php echo $this->formInput( $this->form->get('terms') ); ?>
			<?php echo $this->formElementErrors($form->get('terms')); ?>

			<label for="textfield"></label>
			<?php echo $this->formInput( $this->form->get('buyer_email') ); ?> 
			<?php echo $this->formElementErrors($form->get('buyer_email')); ?>

			<label for="textfield"></label>
			<?php echo $this->formInput( $this->form->get('executive') ); ?> 
			<?php echo $this->formElementErrors($form->get('executive')); ?>

			<!--<input class="btn btn-primary btn-large pull-right" type="submit" value="CREATE&#x00A;LINK">-->
			<button type="submit" class="btn btn-primary btn-large pull-right">CREATE<br/>LINK</button>
			
		</div>
</section>



<div class="checkboxlist clearfix">

<div class="error text-center mb15"><h2><?php echo $product_validate;?></h2></div>

<?php if(is_array($this->products) && !empty($this->products)):?>

		<?php $i=1; foreach($this->products as $key => $catlist):

			$cat_name = $this->categories[$key];
		?>

			<ul id="catlist-<?php echo $key;?>">
				<li><label><input name="categories[]" id="catecheck" type="checkbox" class="chekbx" onclick="select_checkbox('catlist-<?php echo $key;?>')" value="<?php echo $key;?>"> <b>All <?php echo $cat_name;?></b></label></li>

				<?php foreach($catlist as $val):?>

					<li><label><input name="products[<?php echo $key;?>][]" id="list_products" class="chekbx"type="checkbox" value="<?php echo $val['id'];?>"> <?php echo $val['sku'];?></label></li>

				<?php endforeach;?>	
				
			</ul>

			<?php if($i%3==0):?>
				<div class="clearfix"></div>
			<?php endif;?>	

		<?php $i++; endforeach;?>

		<ul>
			<li><label><input name="essential" id="essential" type="checkbox"  value="1"> <b>All Essentials</b></label></li>
			<li><label><input name="clearance" id="clearance" type="checkbox"  value="1"> <b>All clearance</b></label></li>
		</ul>		

    <?php else: ?>
    	<div class="text-center"> <h1>No Products Found </h1></div>
 	<?php endif;?>

</div>

</form>


<script>

function select_checkbox(elm){

	var cat = $("#"+elm).find('#catecheck');

    if(cat.is(':checked')) { // check select status
        $("#"+elm+' .chekbx').each(function() { //loop through each checkbox
            this.checked = true;  //select all checkboxes with class "checkbox1"              
        });
    }else{
        $("#"+elm+' .chekbx').each(function() { //loop through each checkbox
            this.checked = false; //deselect all checkboxes with class "checkbox1"                      
        });        
    }   
}

  $(function() {
    $( "#start_date" ).datepicker({
      defaultDate: "+1w",
      changeMonth: true,
      numberOfMonths: 1,
      dateFormat: "yy-mm-dd",
      onClose: function( selectedDate ) {
        $( "#end_date" ).datepicker( "option", "minDate", selectedDate );
      }
    });
    $( "#end_date" ).datepicker({
      defaultDate: "+1w",
      changeMonth: true,
      numberOfMonths: 1,
      dateFormat: "yy-mm-dd",
      onClose: function( selectedDate ) {
        $( "#end_date" ).datepicker( "option", "maxDate", selectedDate );
      }
    });
  });
  </script>