
<div class="text-center"> <h2>Inventory Upload</h2> </div>
<br/>
<br/>
<br/>
<section class="forminfo1 full clearfix">

    <div class="upload-div">
        <?php 
        	$form = $this->form;
        	$form->prepare(); // The correct enctype is set here ?>
        <?php echo $this->form()->openTag($form); ?>

            
                <?php $fileElement = $form->get('image-file'); ?>
                <?php //echo $this->formLabel($fileElement); ?>
                <?php echo $this->formFile($fileElement); ?>

                <div class="clearfix">
                    <?php echo $this->formElementErrors()
                                ->setMessageOpenFormat('<span class="error">')
                                ->setMessageCloseString('</span>')
                                ->render($fileElement); ?>
                </div>
                
            

            <button class="btn btn-primary btn-large">Submit</button>

        <?php echo $this->form()->closeTag(); ?>
    </div>
</section>

<?php if( $this->success_uploads ): ?>
    <section class="forminfo1 full clearfix success">
      <h3>No of successfull uploads : <span style="font-weight:bold;"><?php echo $this->success_uploads;?></span></h3>
    </section>
<?php endif; ?>

<?php if( count($this->errors) ): ?>
<section class="forminfo1 full clearfix error">
  <h3>Errors in uploading....</h3>
  <ul>
    <?php 
        foreach ($this->errors as $error) 
        {
           echo "<li>$error</li>";
        } 
    ?>
  </ul>
</section>
<?php endif; ?>
