<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Clara Sunwoo (Official Site)</title>        

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/jquery-ui.min.css')); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/custom.js'))
            ->prependFile($this->basePath('js/jquery-ui.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js')); ?>

    </head>
    <body>

        <div class="wrapper">
            <div class="container">

                <!--header start here-->
                <header class="clearfix">
                    <a href="#">
                        <img src="<?php echo $this->basePath('img/logo.jpg');?>" width="93" height="89" alt="Clarasunwoo.com Logo">
                    </a>
                </header>
                 <!--header end here-->  

                <!--content start here-->
                <div class="content_inner clearfix">

                    <?php echo $this->content; ?>

                </div>

                 <!--footer start here-->
                <footer class="clearfix">
                    <div class="footbg"></div>
                    <section>
                        <h2>Clara S. inc</h2>
                        <p>142 W.36th street, fl 14<br>
                          New york, ny  10018</p>
                        <p>P: 212-564-0736</p>
                        <p>F: 212-564-1098</p>
                        <p>E: <a href="mailto:iNFO@clarasunwoo.com">iNFO@clarasunwoo.com</a></p>
                        <p>© 2015 CLARA S. INC</p>
                    </section>
                </footer>
                <!--footer end here-->

            </div>
        </div>        
        

        
            
        <?php echo $this->inlineScript() ?>

    </body>

</html>
